GURU, GURU, GURU

diff --git a/adt b/adt
--- a/adt
+++ b/adt
@@ -26,7 +26,7 @@ CROSS_PREFIX="${BASE_DIR}/adt_build"
 
 function _error
 {
-    echo "### ERROR: ${1}" 1>&2
+    echo "### GURU MEDITATION ERROR (CODE: ${2}): ${1}" 1>&2
     exit "${2}"
 }
 
